name: Python CI - workflow_name

on:
  push:
    branches:
      - main

jobs:
  test-job_name:
    runs-on: ubuntu-latest

    steps:
      - name: print message step_name
        run: echo "Hello From Test Python CI"
